### ISSUE TITLE
[1주차] Algorithm : 그리디

### ISSUE THREAD

**Issue by JerryK026** [techeer-team-e/weekly-studies#1]

**Comment by JerryK026** [comment]
1주차 인증입니다!
https://github.com/JerryK026/javaAlgorithm/tree/master/this_is_coding_test/chapter3

**Comment by ssongedev** [comment]
1주차 인증입니다.
[Greedy](https://github.com/Si-jeong/Algorithms-in-Cpp/tree/main/ThisisCodingTest/Greedy)

**Comment by s-ggul** [comment]
1주차 인증입니다.
<a href="https://github.com/Dudu-CNU/For_Coding_Test/tree/master/%EC%9D%B4%EA%B2%83%EC%9D%B4%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%8B%A4/%EA%B7%B8%EB%A6%AC%EB%94%94">그리디 알고리즘</a>
