### ISSUE TITLE
[9주차] JavaScript : 39장

### ISSUE THREAD

**Issue by JerryK026** [techeer-team-e/weekly-studies#16]

**Comment by ssongedev** [comment]
* 노드
  * DOM 트리: 노드 객체들로 구성된 트리 자료구조
  * 문서 노드, 요소 노드, 어트리뷰트 노드, 텍스트 노드, 공백 텍스트 노드
  * 노드 개체 상속 구조
* 요소 노드 취득
  * Document.prototype.getElementById()
  * Document.prototype/Element.prototype.getElementsByTagName()
  * Document.prototype/Element.prototype.getElementsByClassName()
  * Document.prototype/Element.prototype.querySelector()
  * Document.prototype/Element.prototype.querySelectorAll()
  * -> id 어트리부트가 있는 요소노드: getElementById 메서드, 그 외: querySelector, querySelectorAll 메서드 권장
  * Element.prototype.matches(): 이벤트 위임
  * HTMLCollection, NodeList: DOM 컬렉션 객체 -> 배열로 변환하여 사용 권장(스프레드 문법, Array.from 메서드)
    * HTMLCollection: live 객체
    * NodeList: non-live 객체 (childNodes 프로퍼티가 반환하는 NodeList 객체: live 객체)
* 노드 탐색
  * 자식 노드
    * 탐색: Node.prototype.childNodes, Node.prototype.firstChild, Node.prototype.lastChild (텍스트 노드 o) / Element.prototype.children, Element.prototype.firstElementChild, Element.prototype.lastElementChild
    * 확인: Node.prototype.hasChildNodes() (텍스트 노드 o) / children.length, Element.childElementCount
  * 부모 노드 탐색: Node.prototype.parentNode
  * 형제 노드 탐색: Node.prototype.previousSibling, Node.prototype.nextSibling (텍스트 노드 o) / Element.prototype.previousElementSibling, Element.prototype.nextElementSibling
* 노드 정보 취득: Node.prototype.nodeType, Node.prototype.nodeName
* 요소 노드 텍스트 조작
  * Node.prototype.nodeValue: 텍스트 노드의 텍스트 취득(그 외 null), 변경 
  * Node.prototype.textContext: 요소 노드의 텍스트와 모든 자손 노드의 텍스트 취득(HTML 마크업 무시), 변경(HTML 마크업 파싱 x)
* DOM 조작: 새 노드 생성하여 DOM에 추가, 기존 노드 삭제, 교체
  * Element.prototype.innerHTML: 요소 노드의 HTML 마크업 취득, 변경
    * 단점: 크로스 사이트 스크립팅 공격(XSS)에 취약 (->HTML 새니티제이션), 모든 자식 제거, 삽입 위치 지정 불가
  * insertAdjacentHTML(position, DOMString): 기존 요소 제거x, 위치 지정 삽입, XSS에 취약
  * 노드 생성, 추가
    * Document.prototype.createElement(tagName)
    * Document.prototype.createTextNode(text)
    * Node.prototype.appendChild(childNode)
  * 복수 노드 생성, 추가: DocumentFragment 노드
  * 노드 삽입, 이동: Node.prototype.appendChild(), Node.prototype.insertBefore(newNode, childNode)
  * 노드 복사: Node.prototype.cloneNode([deep: true | false])
  * 노드 교체: Node.prototype.replaceChild(newChild, oldChild)
  * 노드 삭제: Node.prototype.removeChild(child)
* 어트리뷰트: Element.prototype.attributes, NamedNodeMap 객체
  * 조작: Element.prototype.getAttribute()/setAttributes()
  * 확인: Element.prototype.hasAttribute(attributeName)
  * 삭제: Element.prototype.removeAttribute(attributeName)
  * HTML 어트리뷰트 vs. DOM 프로퍼티
    * HTML 어트리뷰트: HTML 요소 초기 상태 저장
    * 요소 노드: 초기 상태 관리(어트리뷰트 노드) & 최신 상태 관리(DOM 프로퍼티)
  * dataset 프로퍼티: HTMLElement.dataset, HTML 요소의 모든 data 어트리뷰트의 정보를 제공하는 DOMStringMap 객체로 반환
* 스타일: HTMLElement.prototype.style
  * 클래스 조작: Element.prototype.className (문자열 반환), Element.prototype.classList (DOMTokenList 객체 반환)
  * 요소에 적용된 CSS 스타일 참조: window.getComputedStyle(element[, pseudo])

**Comment by JerryK026** [comment]
[JS](https://principled-earthquake-2a8.notion.site/39-DOM-3fdf3bb2e4bf402d8b6e4719507e50cc)
