### ISSUE TITLE
[10주차] JavaScript : 40 - 43장

### ISSUE THREAD

**Issue by JerryK026** [techeer-team-e/weekly-studies#19]

**Comment by ww8007** [comment]
[JS 정리](https://github.com/ww8007/TIL/blob/main/JavaScript/Modern_JS_Deep_Dive/README.md)

**Comment by JerryK026** [comment]
[JS](https://principled-earthquake-2a8.notion.site/Deep-Dive-68e0d5b2aa744c76aa62b0322e39ff58)
