### ISSUE TITLE
[1주차] JavaScript : ~ 9장까지

### ISSUE THREAD

**Issue by JerryK026** [techeer-team-e/weekly-studies#2]

**Comment by JerryK026** [comment]
1주차 인증입니다!
https://principled-earthquake-2a8.notion.site/Deep-Dive-68e0d5b2aa744c76aa62b0322e39ff58

**Comment by ssongedev** [comment]
## 1주차 인증

* 새로웠던 부분
  * typeof 연산자가 반환하는 문자열은 7개의 데이터 타입과 정확히 일치하지 않는 것 (p.89)
  * 레이블 문 (p.104)
  * 암묵적 타입 변환 - Truthy 값, Falsy 값 (p.113)
  * 단축 평가 - 논리 연산자를 사용한 단축 평가(&&, ||), 옵셔널 체이닝 연산자(?.), null 병합 연산자(??) (p118)

* 궁금했던 부분
  * 심벌 타입이 ES6에서 새롭게 추가된 이유 (p.67)  
  * JS 객체

**Comment by s-ggul** [comment]
### 1주차 인증
- 기초 문법 복습
- 호이스팅(스코프관련)
- 정적타입과 동적타입 복습
- undefined사용 목적을 이해하였고 이를 통해 null 과 undefined의 이해
