### ISSUE TITLE
[2주차] Algorithm : 그리디 / 실습

### ISSUE THREAD

**Issue by JerryK026** [techeer-team-e/weekly-studies#4]

**Comment by JerryK026** [comment]
2주차 알고리즘 풀이입니다!
[2주차 알고리즘](https://github.com/JerryK026/javaAlgorithm/tree/master/this_is_coding_test/chapter11)

**Comment by s-ggul** [comment]
2주차 알고리즘 풀이입니다! 
<a href='https://github.com/Dudu-CNU/For_Coding_Test/tree/master/%EC%9D%B4%EA%B2%83%EC%9D%B4%EC%BD%94%EB%94%A9%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%8B%A4/%EA%B7%B8%EB%A6%AC%EB%94%94/%EC%8B%A4%EC%A0%84%EB%AC%B8%EC%A0%9C'>그리디 실전문제</a>

**Comment by ssongedev** [comment]
2주차 알고리즘 풀이입니다!
[Greedy 실전문제](https://github.com/Si-jeong/Algorithms-in-Cpp/tree/main/ThisisCodingTest/Greedy)
